name = "statisticalCTMRG"
uuid = "d13d6f25-bd6d-4f03-9d08-8bfc13eb3ea4"
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Revise = "3.12.3"
